### ISSUE TITLE
How to realize the 110 direction stretching?

### ISSUE THREAD

**Issue by Dreamer-zh** [mrkllntschpp/lammps-tutorials#1]
Thank you very much for this tutorial. According to this tutorial, I have realized the tensile mechanical properties of BCC(body centered cubic) Fe block (x - < 100 >, Y - < 010 >, Z - < 001 >).

But I couldn't achieve it when I tried the tensile mechanical properties of another crystal oriented Fe block (x - < 110 >, Y - < 110 >, Z - < 001 >). I have tried to modify the system temperature, cutoff
 and other parameters, but I still can't. I have to ask you for help. I hope you can help me. 

Thank you!

**Comment by Dreamer-zh** [comment]
Other conditions remain unchanged. If I only change this command, the program will report an error.
**Crystal orientation in tutorial:**
lattice bcc ${latparam} orient x 1 0 0 orient y 0 1 0 orient z 0 0 1
**Crystal orientation after transformation**
lattice bcc ${latparam} orient x 1 1 0 orient y -1 1 0 orient z 0 0 1

Error:
Step Lx Ly Lz Press Pxx Pyy Pzz PotEng Temp 
       0        28.55        28.55        28.55 2.5124817e+16 3.7687225e+16 3.7687225e+16   -161074.47 1.0947933e+15          300 
**ERROR: Non-numeric pressure - simulation unstable (../fix_nh.cpp:1043)**
Last command: run         20000

**Comment by mrkllntschpp** [comment]
Thanks!  It turns out that I had defined the "lattice" command twice and the initial one did not have the details of the orientation, so it defaults to the <100> configuration--this caused a problem because the next command used the periodic distance in those directions to set up the simulation cell boundaries.  Then, it built the atoms to the "intended" orientation with the second "lattice" command.  This means that it probably built a bunch of atoms at the boundary that made for a weird atom lattice (not single crystal!).  So...

I went ahead and moved the "lattice" orientation assignment in Tutorials 1, 2, 3, and 4 before the perioidic distance command.  I added an FAQ to Tutorials 1 and 3 about how to do this.  Voila!  Issue resolved.  Not a problem necessarily for <100>, but now it should be easily changed to new orientations.
