### ISSUE TITLE
confusion with strain rate units

### ISSUE THREAD

**Issue by sphCow** [mrkllntschpp/lammps-tutorials#2]
Before I begin, thanks a lot for making these tutorials available. I've a doubt here. In tutorial 3, after the initial equilibration, the simulation box is deformed 

> in the x-direction at a strain rate of 10^10 1/s

That is implemented in the LAMMPS script in the following lines

```
units 		metal
...
timestep 0.001  #in picosecond 
... 
variable srate equal 1.0e10
variable srate1 equal "v_srate / 1.0e12"
fix 2 all deform 1 x erate ${srate1} units box remap x
```
How do you calculate the factor of **1.0e12** ? Isn't the timestep dt involved here in some way?

**Comment by claireb5112** [comment]
Hello! I think it is because the pico prefix value is 1e-12. So dividing the srate by 1e12 (or multiplying by 1e-12) you are converting srate in sec to pico sec. So your total time for the calculation is 10^10 seconds (1e10) and you are having the time step be a pico second. ? Hopefully the writer of this code can verify, but those are my thoughts.

**Comment by mrkllntschpp** [comment]
Thanks!  I went ahead and added this to the FAQ section.  Claireb5112, you were almost right on all accounts.  It is a unit conversion.  The total time isn't 10^10, that is just the strain rate; and the timestep isn't picosecond, but rather 0.001 picosecond (femtosecond, 1e-15 s).  I added a little more explanation in the FAQ.
